### ISSUE TITLE
Couldn't read block from Mifare Classic

### ISSUE THREAD

**Issue by yboenec** [svvitale/nxppy#13]
Hi,

We are trying to use your library in our project with NXP Explore NFC card PN512. We have been able to read blocks from Mifare UltraLight but when it comes to Mifare Classic we can only read UID. We have got "ReadError: read failed: 782". Maybe It's the block size ? or Explore NFC proprietary driver? 

Thank you,

**Comment by svvitale** [comment]
Sorry, Mifare Classic is not supported yet.  See #5 .
