### ISSUE TITLE
How to compile with python3?

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [svvitale/nxppy#27]
Hello,

Could you tell me how compile this library for python3 please?

Thank you very much.

**Comment by svvitale** [comment]
Hi @juanmiguelRuaDev,

It's very similar to the Python 2 instructions:

Install pip for Python 3:
```
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
```

Install nxppy for Python 3:
```
sudo pip3 install nxppy
```

**Comment by juanmiguelRuaDev** [comment]
Thanks,
