### ISSUE TITLE
Mifare Read Issue

### ISSUE THREAD

**Issue by clafouti2104** [svvitale/nxppy#3]
Hello,

First, thanks for the library, it looks like fantastic. 
Unfortunately, I got some problems using it. 
I'd like to read a mifare tag and make a http request.
Using the card_polling c script, I manage to read the tag but not using your library.
To dig a litte more, I create this little script:

```
import nxppy

uid = nxppy.read_mifare()
print uid
```

Which gives me the following error:

```
root@raspberrypi:/home/pi/nxpnfc# python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    uid = nxppy.read_mifare()
AttributeError: 'module' object has no attribute 'read_mifare'
```

I also try your example:

```
import nxppy

print "Imported NXPPY"
mifare = nxppy.Mifare()
print "Loaded mifare device"
print mifare
uid = mifare.select()
print "Selected card from device"
print "Card ID:" + uid
```

And the output:

```
root@raspberrypi:/home/pi/nxpnfc# python test.py
Imported NXPPY
Loaded mifare device
<nxppy.Mifare object at 0xb6d0a5a0>
Segmentation fault
```

Can you help me please?

Thanks a lot

**Comment by toufou** [comment]
Hi,

Is someone find a solution?

I just install last raspbian distribution, install manually nxppy 1.3.1 and try without card and have the error: 
 uid = nxppy.read_mifare()
AttributeError: 'module' object has no attribute 'read_mifare'

is there a way to fix that?

thanks,
TouFou

**Comment by svvitale** [comment]
Hi @toufou, 

Please check the readme.  The read_mifare function is no longer used.  There's a complete example in the readme.

-Scott

**Comment by toufou** [comment]
It works!!

Thank you Scott!!

You did a very good job!
thanks again!
