### ISSUE TITLE
ID read from NFC is different from the ID put into the NFC

### ISSUE THREAD

**Issue by helxsz** [svvitale/nxppy#32]
I am using the TagWriter to write '00000001' text into NFC card, however when i am using the element14 NXP card to read the data, the text based ID i read is 'DB1493AE'.  Is there a conversion, how to fix this?

**Comment by helxsz** [comment]
hi, @svvitale  do you know why ?

**Comment by svvitale** [comment]
Hi, @helxsz, sorry for not getting back to you sooner.  Which block are you writing into?  Also, the `write_block()` method only supports writing 4 bytes at a time.

**Comment by svvitale** [comment]
Closing since I haven't heard back in a couple months.  Please let me know if you're still encountering the issue and would like further help.
