### ISSUE TITLE
Installing nxppy breaks explorenfc-basic Example

### ISSUE THREAD

**Issue by punkadiddle** [svvitale/nxppy#35]
When installing nxppy all the system libs are build and installed for systemwide use. After that explorenfc-basic fails:
`pi@raspberrypi:~ $ explorenfc-basic
Waiting for tag or device...
on_name_lost(): :org.neardal

(explorenfc-basic:11092): GLib-GIO-WARNING **: Received property Iso14443aUid with type ay does not match expected type s in the expected interface

(explorenfc-basic:11092): GLib-GIO-WARNING **: Received property Iso14443aAtqa with type ay does not match expected type s in the expected interface

(explorenfc-basic:11092): GLib-GIO-WARNING **: Received property Iso14443aSak with type ay does not match expected type s in the expected interface
Tag found
Segmentation fault`

Removed the libraries from /usr/local/lib and reinstalling the NXP software from it's deb files and explorenfc-basic works again. I checked that both deb files and what nxppy was downloading had the same version numbers.

Also libwiring delivered together with the nxp debs was older than the one on my Pi3. It's probably not a good idea to just pull all these libs and install them for system wide use.

**Comment by svvitale** [comment]
This has been resolved in the latest release (1.4.0).  nxppy no longer depends on wiringPi and neardal, so there will not be a conflict with the system libraries.  Of course, if the EXPLORE-NFC is actively being used by a different process, it will not be accessible from nxppy and vice versa.  Closing this issue for now, please re-open if you still encounter issues after upgrading.
