### ISSUE TITLE
NXPPY in python3

### ISSUE THREAD

**Issue by AlterCodex** [svvitale/nxppy#36]
I'm trying to work NXXPY using python3  and it shows the following error:
AttributeError: 'module' object has no attribute 'Myfare'
any idea?

**Comment by svvitale** [comment]
Try "Mifare"

**Comment by AlterCodex** [comment]
That was a typo the error is AttributeError: 'module' object has no attribute 'Mifare'
 I'm trying to remake the setup that run on python3 but it's doesn't works.

**Comment by AlterCodex** [comment]
It was a problem on the python3 of my raspberry, I reinstall it and run:
sudo python3 setup.py build install
