### ISSUE TITLE
Python version not supported

### ISSUE THREAD

**Issue by sp4tz** [svvitale/nxppy#40]
Hi there!

Im trying to install nxppy on the latest raspbian Jessy OS and python 2.7.9

after installing all dependencies, i try to run 
`sudo pip install nxppy `

and i get every time this error: Python version not supported

**Comment by svvitale** [comment]
My apologies, @sp4tz!  I've just rolled version 1.4.1 and verified that it correctly installs on Python 2.7 now.  Try installing via pip again.

**Comment by sp4tz** [comment]
Thx, it works now!
