### ISSUE TITLE
Some environments require -fPIC

### ISSUE THREAD

**Issue by nils-werner** [svvitale/nxppy#48]
Unfortunately, the contents of `nxp/` are not compiled using the `-fPIC` flag, which prevents my version of Python of linking against it. A fix is to change `get_nxpRdLib.sh:29`

    cmake ..

to

    CFLAGS=-fPIC cmake ..

If you like I can create a PR so you can test this against your environment.

**Comment by svvitale** [comment]
Thanks for all the help, @nils-werner!  I'll roll these up into a release once I finish some other changes I've been working on.
