### ISSUE TITLE
Reading from AS3955

### ISSUE THREAD

**Issue by benkli** [svvitale/nxppy#57]
Please answer these questions as part of your new issue.

##### Which version of Python are you using?
2.7.9
##### Which OS and version are you running?
Linux raspberrypi 4.4.38-v7+
##### Is SPI enabled?
yes
##### Are you trying to read/write a Mifare Classic card?  (This is currently unsupported)
I'm trying to read an AMS AS3955 NFC interface tag. This tag acts as an NFC type 2 tag (mifare ultralight)

Hey there!
I'm trying to read data from an AMS AS3955 NFC interface tag.
When reading and writing from EEPROM data section 0 -> 127 everthing works fine.
But when I'm trying to read from the AS3955 extendend memory section (0xfc -> 0xff),
I'm getting: 

> nxppy.ReadError: Nxppy: Protocol Error, response violated protocol from Mifare PAL-Component

According to the AS3955 datasheet, I can access this area via normal read and write commands. Writing to this section works, I can read the written data with the MCU attached to the AS3955. But I can not read the data from this section with nxppy.
I've run out of ideas. Thank you in advance for your help!

Yours, Benjamin

**Comment by benkli** [comment]
Strange! When reading from memory 0xfc alone, an error does not occure. But the returned data is always 0.

**Comment by svvitale** [comment]
Was the `MFC_BLOCK_DATA_SIZE` the only change you made?  Any other side effects that you can tell?  If not, I'd like to merge your changes into master.  Mind filing a pull request?

**Comment by benkli** [comment]
Hi Scott!
I copied the mifare_read(...) function and made a second one named mifare_read16(...). This one had the changed MFC_BLOCK_DATA_SIZE=16 in it. This solution enabled me to interface the AS3955’s buffer. I Couldn’t recognize any side effects. 

I’m an electrical engineer and not very familiar with the git terminology, so I’m not quite sure what a pull request is. J

 

With best regards

Benjamin

 

Von: Scott Vitale <notifications@github.com>
Antworten an: svvitale/nxppy <reply@reply.github.com>
Datum: Donnerstag, 10. August 2017 um 15:40
An: svvitale/nxppy <nxppy@noreply.github.com>
Cc: benkli <benjamin.moesslang@student.tugraz.at>, State change <state_change@noreply.github.com>
Betreff: Re: [svvitale/nxppy] Reading from AS3955 (#57)

 

Was the MFC_BLOCK_DATA_SIZE the only change you made? Any other side effects that you can tell? If not, I'd like to merge your changes into master. Mind filing a pull request?

**Comment by svvitale** [comment]
Ah, no problem.  I'll give it a try using your description and we can go from there.  I'll ping you again when I need a guinea pig :).  I'll reopen this issue since it is something that needs to be fixed.
