### ISSUE TITLE
Request to add updated ordering info link to readme

### ISSUE THREAD

**Issue by eecharlie** [svvitale/nxppy#63]
The uk.farnell link in your readme is a product page listing the explorer board as 'no longer stocked'. A similar link took me to a distributor called CPC which only ships to the UK. 

The catalog link that did work for me (and ships to many countries, including UK and US) is:

https://www.newark.com/nxp/explore-nfc-ww/nfc-add-on-board-raspberry-pi/dp/45X6356

Thanks,

Charlie

**Comment by svvitale** [comment]
Updated, thanks!
