### ISSUE TITLE
nxp.zip removed

### ISSUE THREAD

**Issue by dosenfisch** [svvitale/nxppy#66]
The installer can't open the nxp.zip.

>   [nxp.zip]
    End-of-central-directory signature not found.  Either this file is not
    a zipfile, or it constitutes one disk of a multi-part archive.  In the
    latter case the central directory and zipfile comment will be found on
    the last disk(s) of this archive.
   unzip:  cannot find zipfile directory in one of nxp.zip or
   nxp.zip.zip, and cannot find nxp.zip.ZIP, period.

 
If I try to open the corresponding link  with my browser, I get "This link has been removed."

> https://nxp1.sharepoint.com/sites/6_1/S&CExternal/_layouts/15/guestaccess.aspx?docid=0afe70cb96bba406d9c3c27534d03087d&authkey=AU04PywGBtgqJtk4Fp0GT0M"``

##### Which version of Python are you using?
2.7.13

##### Which OS and version are you running?
Raspbian

##### Is SPI enabled?
Yes

##### Are you trying to read/write a Mifare Classic card?  (This is currently unsupported)
No

**Comment by svvitale** [comment]
Duplicate to #55.
