### ISSUE TITLE
problem on step (uid = mifare.select() ) nothing happens.

### ISSUE THREAD

**Issue by Hvorost** [svvitale/nxppy#70]
Please answer these questions as part of your new issue.

##### Which version of Python are you using?
2.7 and 3.4
##### Which OS and version are you running?
Raspbian Jessie and raspbian stretch
##### Is SPI enabled?
yes

Hello , I have  a problem when I try select uid, also when I try to read/write function. On this step nothing happends! The process is stuck and no one error message. Maybe I can't use this library with my NXP Chip https://www.nxp.com/products/identification-and-security/nfc/nfc-reader-ics/development-kits-for-pn7120-plugn-play-nfc-controller:OM5577

**Comment by svvitale** [comment]
This library is only compatible with the EXPLORE-NFC which is PN512 based.
