### ISSUE TITLE
sudo apt-get install nxprdlib doesn't work

### ISSUE THREAD

**Issue by nils-werner** [svvitale/nxppy#75]
When trying to install nxppy the following message appears:

    NXP Reader library not found.  Install it using `sudo apt-get install nxprdlib`

however when running said command, `apt-get` can't find that package. Are you certain the package exists in the Raspian repositories?

The readme mentions a different installation routine altogether...

**Comment by svvitale** [comment]
Yes, you're correct, the NXP Reader library is not available in the Raspbian repos.  I'll get that error message cleaned up.  The procedure in the README is correct.
