### ISSUE TITLE
nxppy.WriteError= Write failed: 201

### ISSUE THREAD

**Issue by toby314** [svvitale/nxppy#8]
block=10
number = 1000

while 1
    try:
        mifare.write_block(block, str(number) )
        print "write block ",str(number)
        return(1)
    except nxppy.WriteError, ex:
        print "nxppy.WriteError=", ex
        return(0)
...     
     
     number = number -1
  #   read_block etc
---------
nxppy.WriteError= Write failed: 201

This happens intermittently about 1 in 20 times
 
It writes correctly to the card but gives this error.
ideally if it writes correctly then it shouldnt create an exception ???

**Comment by svvitale** [comment]
The write command will raise if it receives an error status from the NXP Reader Library.  The 0x200 piece of the return code indicates that it's an error from the HAL component code:

```c
#define PH_COMP_HAL                     0x0200U /**< HAL Component Code. */
```

And the error code is:

```c
#define PH_ERR_IO_TIMEOUT               0x0001U /**< No reply received, e.g. PICC removal. */
```

So it looks as if the reader did not receive a response from the tag indicating that the write succeeded.  It did, in fact, succeed, but there's no way to ensure that status.  My recommendation would be to implement a retry mechanism when this error code is encountered.
